
server.port=8089

# SQL Server #
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://127.0.0.1:1433;databaseName=miniproject
spring.datasource.username=NMES
spring.datasource.password=NMES

# thymeleaf #
spring.thymeleaf.check-template-location=true
spring.thymeleaf.enabled=true
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# JPA-Hibernate #
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

#For synchronization with naming of the MES DB
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Develop #
spring.jpa.show-sql=true
#spring.jpa.hibernate.format_sql=true
spring.jpa.open-in-view=true
spring.thymeleaf.cache=false
spring.jpa.hibernate.ddl-auto=update
# Release #
#spring.jpa.show-sql=false
#spring.jpa.open-in-view=false
#spring.thymeleaf.cache=false
#spring.jpa.hibernate.ddl-auto=none

